### PR TITLE
vince: Enable CI

### PR DESCRIPTION
**Pull request by raza231198**

### CODE REVIEW

**Comment by rokibhasansagar** [comment]
Delete the PB_OFFICIAL switch from BC and force push here.

**Comment by rokibhasansagar** [comment]
Looks good to me.
But @raza231198, Adding CHANGELOG & MAINTAINER in config is recommended.

**Comment by rokibhasansagar** [comment]
When force-push the new changes, Squash-and-Merge the PR with nice Commit Message.

**Comment by raza231198** [comment]
@rokibhasansagar changelog and maintainer in official build 🤓

**Comment by rokibhasansagar** [comment]
Branch changed as per new convention. Branch names will be as the OmniROM's platform names i.e., __android-X.Y__

**Pull request merged**
